Repository Cibiyanna26/EffiTrack, pull requests merged in 2024-01, with the labels that each got.

#52 fixed light mode and dark mode bug and upcoming contest bug
  FrontEnd/src/components/Dashboard/Home.js
  FrontEnd/src/components/Dashboard/Main.js
  FrontEnd/src/components/Dashboard/Mid.js
  FrontEnd/src/components/Dashboard/Navbar.js
  FrontEnd/src/components/Dashboard/Profile.js
  FrontEnd/src/components/Dashboard/Theme.js
  FrontEnd/src/components/LoginCred/LoginForm.js
  FrontEnd/src/components/LoginCred/SignupForm.js
  FrontEnd/src/components/ProfilePage/Platform.username.js
  FrontEnd/src/services/servicehelp.js
  backend/controllers/futureContestController.js
  backend/controllers/githubControllers.js
  backend/utils/generateToken.js
Labels: bug

#58 added logos and changed in your repo section
  FrontEnd/src/assets/codechef-01.png
  FrontEnd/src/assets/codechef-02.png
  FrontEnd/src/components/Dashboard/Card.js
  FrontEnd/src/components/Dashboard/Mid.js
  FrontEnd/src/components/Dashboard/Showcase.js
Labels: enhancement

#64 Fixed UI of Github profile
  FrontEnd/src/components/Dashboard/GitProfile.js
  FrontEnd/src/components/Dashboard/Showcase.js
Labels: enhancement

#72 69 signup failed replace cookie
  FrontEnd/.env
  FrontEnd/src/components/Dashboard/Card.js
  FrontEnd/src/components/Dashboard/Home.js
  FrontEnd/src/components/Dashboard/Leftnav.js
  FrontEnd/src/components/Dashboard/Showcase.js
  FrontEnd/src/components/LoginCred/SignupForm.js
  LICENSE
Labels: bug, enhancement

#80 75 navigation issue
  CODE_OF_CONDUCT.md
  FrontEnd/src/App.js
  FrontEnd/src/components/Dashboard/Home.js
  FrontEnd/src/components/Dashboard/Leftnav.js
  FrontEnd/src/components/Dashboard/Main.js
  FrontEnd/src/components/Dashboard/Navbar.js
  FrontEnd/src/components/Dashboard/Theme.js
  FrontEnd/src/components/LoginCred/LoginForm.js
  FrontEnd/src/components/ProfilePage/Demoprofile.js
  FrontEnd/src/components/usernameValidate/usernameValidation.js
  FrontEnd/src/index.css
  FrontEnd/src/index.js
  FrontEnd/src/redux/commonSlice.js
  FrontEnd/src/redux/store.js
  LICENSE
  node_modules/.package-lock.json
Labels: enhancement
